print("we are about to calculate the area of a rectangle")
base = input("what is the base?:")
height = input("what is the height?:")
area = int(base) *int(height)
print("The area of the rectangle is {}".format(area))
print("We are about to calculate the area of a triangle")
base = input("what is your base?:")
height = input("what is your height?:")
area =0.5 * int(base) * int(height) 
print("The area of a triangle is {}".format(area))
print("We are about to calculate the area of a circle")
radius = input('what is the radius')
area = 22/7 * int(radius) * int(radius)
print("The area of the circle is {}".format(area))