print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
def add_two(first_value,second_value):
    first_value= int(first_value)
    second_value= int(second_value)
    first_value input("what is your first value?")
    second_value input("what is your second value?")
    print(add_two(first_value + second_value))